# Generated by Django 2.0.3 on 2019-05-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_year',
        ),
    ]
